В синхронном коде ошибка вызывает немедленное завершение программы
Как обстоят дела с асинхронными вызовами?

async () => {

}
